collections:
  - name: awx.awx
    version: 19.1.0
  - name: community.crypto
    version: 1.9.5
  - name: community.digitalocean
    version: 1.9.0
  - name: community.general
    version: 3.6.0
  - name: kubernetes.core
    version: 2.1.1
  - name: vyos.vyos
    version: 2.0.0
  # - name: https://github.com/TerryHowe/ansible-modules-hashivault.git
  #   type: git
  #   version: 4.6.4
