collections:
  - name: awx.awx
    version: 19.1.0
  - name: community.digitalocean
    version: 1.9.0
  - name: kubernetes.core
    version: 2.1.1
  # - name: https://github.com/TerryHowe/ansible-modules-hashivault.git
  #   type: git
  #   version: 4.6.4
