- name: install nginx and php-fpm
  ansible.builtin.apt:
    state: present
    name:
      - nginx
      - php-fpm
    update_cache: true
  become: true

- name: set php-fpm version for x86_64 (bionic)
  ansible.builtin.set_fact:
    php_fpm_version: 7.2
  when:
    - ansible_architecture == 'x86_64'
    - ansible_distribution_release == 'bionic'

- name: set php-fpm version for x86_64 (focal)
  ansible.builtin.set_fact:
    php_fpm_version: 7.4
  when:
    - ansible_architecture == 'x86_64'
    - ansible_distribution_release == 'focal'

- name: set php-fpm version for x86_64
  ansible.builtin.set_fact:
    php_fpm_version: 7.3
  when: ansible_architecture == 'armv7l'

- name: check if /etc/nginx/sites-enabled/default exists
  ansible.builtin.stat:
    path: /etc/nginx/sites-enabled/default
  register: default
  become: true

- name: move /etc/nginx/sites-enabled/default out of the way
  ansible.builtin.file:
    state: absent
    path: /etc/nginx/sites-enabled/default
  when: default.stat.islnk is defined
  notify: reload nginx
  become: true

- name: deploy /etc/nginx/conf.d/default.conf
  ansible.builtin.copy:
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
    backup: true
    content: |
      server {
        listen *:8000 default_server;
        access_log /var/log/nginx/http.access.log combined;
        error_log /var/log/nginx/http.error.log;
        root /usr/share/nginx/html/cloudmason.org;
        index index.php index.html index.htm;
        location / {
          try_files $uri $uri/ index.php =404;
        }
        location ~ \.php$ {
          try_files $uri =404;
          fastcgi_pass unix:/run/php/php{{ php_fpm_version }}-fpm.sock;
          include /etc/nginx/fastcgi_params;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
        location /minecraft {
          autoindex on;
        }
      }
  become: true
  notify: reload nginx

- name: start and enable nginx and phpX-fpm
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - nginx
    - php{{ php_fpm_version }}-fpm
  become: true

- name: create cloudmason.org base directory
  ansible.builtin.file:
    state: directory
    path: /usr/share/nginx/html/cloudmason.org
    owner: root
    group: root
    mode: 0755
  become: true
  notify: Reload nginx

- name: deploy cloudmason.org site
  ansible.builtin.copy:
    src: "cloudmason.org/{{ item }}"
    dest: "/usr/share/nginx/html/cloudmason.org/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  become: true
  loop:
    - android-chrome-192x192.png
    - android-chrome-512x512.png
    - apple-touch-icon.png
    - favicon-16x16.png
    - favicon-32x32.png
    - favicon.ico

- name: deploy cloudmason.org site
  ansible.builtin.template:
    src: "cloudmason.org/{{ item }}"
    dest: "/usr/share/nginx/html/cloudmason.org/{{ item }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  become: true
  loop:
    - README.md
    - cloudmason.php
    - graphs.php
    - keybase.txt
    - media.php
    - site.webmanifest

- name: symlink cloudmason.php to index.php
  ansible.builtin.file:
    state: link
    src: /usr/share/nginx/html/cloudmason.org/cloudmason.php
    dest: /usr/share/nginx/html/cloudmason.org/index.php
    force: true
  become: true

- name: install fping, fortune and fortunes
  ansible.builtin.apt:
    state: present
    name:
      - fping
      - fortune
      - fortunes
      - fortunes-bofh-excuses
  become: true
