- name: debug
  ansible.builtin.debug:
    msg: |
      {{ item.key }}
      {{ item.value.lastpass }}
      {{ item.value.vault}}
      {{ (lookup('community.general.lastpass', item.value.lastpass, field='notes') | from_json)['vault'] }}
  loop: "{{ lookup('dict', maps, wantlist=true) }}"
  no_log: true

- name: lastpass => vault
  hashivault_secret:
    secret: "{{ item.value.vault }}"
    data: "{{ (lookup('community.general.lastpass', item.value.lastpass, field='notes') | from_json)['vault'] }}"
  loop: "{{ lookup('dict', maps, wantlist=true) }}"
  no_log: true
