- name: lastpass => vault
  hashivault_secret:
    secret: "{{ item.vault }}"
    data: "{{ lookup('community.general.lastpass', item.lastpass, field='notes') }}"
  no_log: true
  loop: "{{ maps }}"

- name: debug
  ansible.builtin.debug:
    msg: "LastPass( {{ item.lastpass }} ) => Vault( {{ item.vault }} )"
  loop: "{{ maps }}"
