- name: lastpass => vault
  hashivault_secret:
    mount_point: "{{ (lookup('community.general.lastpass', item['lastpass'], field='notes') | from_json)['vault']['mount_point'] }}"
    secret: "{{ (lookup('community.general.lastpass', item['lastpass'], field='notes') | from_json)['vault']['secret'] }}"
    data: "{{ (lookup('community.general.lastpass', item['lastpass'], field='notes') | from_json)['vault']['data'] }}"
  loop: "{{ secrets }}"
