---
- name: awx
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:

    - name: organizations
      ansible.builtin.include_role:
        name: awx
        tasks_from: organizations.yml
        vars_from: organizations.yml

    - name: teams
      ansible.builtin.include_role:
        name: awx
        tasks_from: teams.yml
        vars_from: teams.yml

    - name: users
      ansible.builtin.include_role:
        name: awx
        tasks_from: users.yml
        vars_from: users.yml
