---
- name: awx
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:

    - name: loop create awx assets
      ansible.builtin.include_role:
        name: awx
        tasks_from: "{{ thing ~ '.yml' }}"
        vars_from: "{{ thing ~ '.yml' }}"
      loop:
        - organizations
        - teams
        - users
        - projects
        - inventories
        - inventory_sources
        - credentials
        - notification_templates
        - job_templates
        - schedules
        - execution_environments
      loop_control:
        loop_var: thing
