---
- name: clusterpi
  hosts: clusterpi:!clusterpi3
  connection: ssh
  gather_facts: true
  become: false

  handlers:

    - name: restart tailscaled
      ansible.builtin.systemd:
        name: tailscaled
        state: restarted
      become: true

  tasks:

    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
      notify: restart tailscaled
      become: true

    - name: include latest
      when: latest | default(false, true)
      ansible.builtin.include_role:
        name: ubuntu
        tasks_from: latest.yml

    - name: include packages
      when: packages | default(false, true)
      ansible.builtin.include_role:
        name: ubuntu
        tasks_from: packages.yml

    - name: include user (mark)
      when: mark | default(false, true)
      ansible.builtin.include_role:
        name: ubuntu
        tasks_from: user/mark.yml

    - name: include user (concourse)
      when: concourse | default(false, true)
      ansible.builtin.include_role:
        name: ubuntu
        tasks_from: user/concourse.yml

    - name: set leader options
      ansible.builtin.set_fact:
        k3s_options: "--cluster-init"
        fetch_kubeconfig: true
      when:
        - k3s | default(false, true)
        - inventory_hostname == "clusterpi0"

    - name: set member options
      ansible.builtin.set_fact:
        k3s_options: "--server https://clusterpi0.cloudmason.org:6443"
        fetch_kubeconfig: false
      when:
        - k3s | default(false, true)
        - inventory_hostname != "clusterpi0"

    - name: include k3s
      when: k3s | default(false, true)
      ansible.builtin.include_role:
        name: k3s
        tasks_from: main
      vars:
        version: v1.19.15%2Bk3s2
        binary: k3s-armhf
        sha256: d3250017ac051b9aa3e03a6dd80f2a2696502e4385eb14df9f0964ac8905eaa4
        token: "{{ (lookup('community.general.lastpass', 'Homelab\Ansible/K3s', field='notes') | from_json)['token'] }}"
        options: "{{ k3s_options }} --disable servicelb --write-kubeconfig-mode 0644"

    - name: include tailscale role (main tasks)
      when: tailscale | default(false, true)
      ansible.builtin.include_role:
        name: tailscale
        tasks_from: main.yml
