---
- name: powerdns
  hosts: powerdns
  connection: ssh
  gather_facts: true
  become: false
  tasks:
    - name: include powerdns role (rasbian tasks)
      ansible.builtin.include_role:
        name: powerdns
        tasks_from: raspian.yml
      when: ansible_architecture == "armv7l"
    - name: include powerdns role (ubuntu tasks)
      ansible.builtin.include_role:
        name: powerdns
        tasks_from: ubuntu.yml
