---
- name: secrets
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: include secrets role (main tasks)
      ansible.builtin.include_role:
        name: secrets
        tasks_from: main.yml
      vars:
        secrets:
          - lastpass: Homelab\Concourse/AWX/users/mark
          - lastpass: Homelab\Concourse/AWX/credentials/github
          - lastpass: Homelab\Concourse/AWX/credentials/awx
          - lastpass: Homelab\Concourse/AWX/credentials/mark
          - lastpass: Homelab\Concourse/AWX/credentials/mamercad
          - lastpass: Homelab\Concourse/AWX/credentials/ansible-vault
          - lastpass: Homelab\Concourse/AWX/credentials/slack
          - lastpass: Homelab\Concourse/AWX/credentials/healthchecks-io
          - lastpass: Homelab\Concourse/OctoDNS/cloudflare
          - lastpass: Homelab\Concourse/OctoDNS/powerdns
          - lastpass: Homelab\Concourse/Dotfiles/mark
