---

- name: ping
  hosts: all:!unifi_aps
  connection: ssh
  gather_facts: false
  become: false
  tags: ping
  tasks:
    - name: ping
      ansible.builtin.ping:

- name: uptime
  hosts: unifi_aps
  connection: ssh
  gather_facts: false
  become: false
  tags: uptime
  tasks:
    - name: uptime
      ansible.builtin.raw: uptime
      register: uptime
      changed_when: '"load average" not in uptime.stdout'

# - name: powerdns
#   hosts: powerdns
#   connection: ssh
#   gather_facts: true
#   become: false
#   tags: powerdns
#   tasks:
#     - name: include powerdns role (rasbian tasks)
#       ansible.builtin.include_role:
#         name: powerdns
#         tasks_from: raspian.yml
#       when: ansible_architecture == "armv7l"

# - name: wan
#   hosts: gateway
#   connection: ssh
#   gather_facts: false
#   become: false
#   tags: octodns
#   tasks:
#     - name: include octodns role (wan tasks)
#       ansible.builtin.include_role:
#         name: octodns
#         tasks_from: wan.yml
#         apply:
#           tags: wan
#       tags: always

# - name: octodns
#   hosts: localhost
#   connection: local
#   gather_facts: false
#   become: false
#   tags: octodns
#   tasks:
#     - name: include octodns role (main tasks)
#       ansible.builtin.include_role:
#         name: octodns
#         tasks_from: main.yml
#       vars:
#         doit: true
#       tags: always

# - name: traefik
#   hosts: traefik
#   connection: ssh
#   gather_facts: true
#   become: false
#   tags: traefik
#   tasks:
#     - name: include traefik role (rasbian tasks)
#       ansible.builtin.include_role:
#         name: traefik
#         tasks_from: raspian.yml
#       when: ansible_architecture == "armv7l"
