---
- name: tailscale
  hosts: ubuntu
  connection: ssh
  gather_facts: true
  become: false
  tasks:
    - name: include tailscale role (main tasks)
      ansible.builtin.include_role:
        name: tailscale
        tasks_from: main.yml
