---
- name: test2
  hosts: "{{ ansible_limit | default('localhost', true) }}"
  connection: "{{ 'local' if ansible_limit | default('localhost', true) == 'localhost' else 'ssh' }}"
  gather_facts: true
  become: false

  tasks:

    # - name: debug
    #   ansible.builtin.debug:
    #     var: ansible_facts

    - name: debug
      ansible.builtin.debug:
        msg: |
          {{ ansible_facts.keys() | sort }}

    # - name: debug
    #   ansible.builtin.debug:
    #     msg: |
    #       {{ ansible_facts.keys() | sort | length }}

    - name: debug
      ansible.builtin.debug:
        msg: |
          {{ hostvars[inventory_hostname]["ansible_facts"].keys() | sort }}
