---
- name: test2
  hosts: "{{ ansible_limit | default('localhost', true) }}"
  connection: "{{ 'local' if ansible_limit | default('localhost', true) == 'localhost' else 'ssh' }}"
  gather_facts: true
  become: false

  tasks:

    - name: show _foo
      ansible.builtin.debug:
        msg: |
          ansible_facts["_foo"]: {{ ansible_facts["_foo"] }}
          hostvars[inventory_hostname]["ansible_facts"]["_foo"]: {{ hostvars[inventory_hostname]["ansible_facts"]["_foo"] }}

    - name: show _bar
      ansible.builtin.debug:
        msg: |
          ansible_facts["_bar"]: {{ ansible_facts["_bar"] }}
          hostvars[inventory_hostname]["ansible_facts"]["_bar"]: {{ hostvars[inventory_hostname]["ansible_facts"]["_bar"] }}
