---
- name: test1
  hosts: "{{ ansible_limit | default('localhost', true) }}"
  connection: "{{ 'local' if ansible_limit | default('localhost', true) == 'localhost' else 'ssh' }}"
  gather_facts: true
  become: false

  tasks:

    - name: set a fact
      ansible.builtin.set_fact:
        foo: bar
