---
- name: testing1
  hosts: all
  connection: ssh
  gather_facts: false
  become: false
  tasks:

    - name: ping
      ansible.builtin.ping:

    - name: include testing role
      ansible.builtin.include_role:
        name: testing
        tasks_from: main.yml

    - name: fail
      ansible.builtin.fail:
      when: 3 | random == 1

    # - name: debug
    #   ansible.builtin.debug:
    #     msg: hello
    # - name: fail
    #   ansible.builtin.fail:

# - name: testing2
#   hosts: localhost
#   connection: local
#   gather_facts: false
#   become: false
#   tasks:
#     - name: ping
#       ansible.builtin.ping:
#     - name: fail
#       ansible.builtin.fail:
