---
- name: testing play
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  vars:

      xxx: a
      yyy: b
      zzz: c

  tasks:

    - name: debug
      ansible.builtin.debug:
        msg: |
          xxx: {{ xxx }}
          yyy: {{ yyy }}
          zzz: {{ zzz }}
