---
- name: testing play
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  vars:

      xxx: a
      yyy: b
      zzz: c

  tasks:

    - name: pause
      ansible.builtin.pause:
        seconds: 0
        prompt: |
          xxx: {{ xxx }}
          yyy: {{ yyy }}
          zzz: {{ zzz }}
          www: {{ www | default('<undefined>', true) }}
