---
- name: test1
  hosts: "{{ ansible_limit | default('localhost', true) }}"
  connection: "{{ 'local' if ansible_limit | default('localhost', true) == 'localhost' else 'ssh' }}"
  gather_facts: true
  become: false

  tasks:

    - name: set a fact _foo=bar (cacheable)
      ansible.builtin.set_fact:
        _foo: bar
        cacheable: true

    - name: set a fact _bar=foo (not cacheable)
      ansible.builtin.set_fact:
        _bar: foo
        cacheable: false
