---

- name: unifi
  hosts: unifi,&gateway
  connection: ssh
  gather_facts: false
  become: false
  tasks:
    - name: usg
      ansible.builtin.include_role:
        name: unifi
        tasks_from: usg.yml

- name: usg
  hosts: usg
  connection: network_cli
  gather_facts: false
  become: false
  tasks:
    - name: vyos
      ansible.builtin.include_role:
        name: unifi
        tasks_from: vyos.yml

- name: unifi
  hosts: unifi,&cloudkey
  connection: ssh
  gather_facts: false
  become: false
  tasks:
    - name: usg
      ansible.builtin.include_role:
        name: unifi
        tasks_from: cloudkey.yml

- name: letsencrypt
  hosts: cloudkey
  connection: ssh
  gather_facts: false
  become: false
  tasks:
    - name: letsencrypt
      ansible.builtin.include_role:
        name: unifi
        tasks_from: letsencrypt.yml
      when: false  # not well tested
