---
- name: vault
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: include vault role (main tasks)
      ansible.builtin.include_role:
        name: vault
        tasks_from: main.yml
      vars:
        context: thinkpad
        vault_values:
          server:
            dev:
              enabled: true
          ui:
            enabled: true
            serviceType: LoadBalancer
