credentials:
  - name: Cloudmason GitHub
    description: Cloudmason
    organization: Cloudmason
    credential_type: Source Control
    inputs:
      ssh_key_data: "{{ lookup('env', 'AWX_CREDENTIALS_CLOUDMASON_GITHUB_SSH_KEY') | b64decode }}"
  - name: Cloudmason Machine (awx)
    description: Cloudmason
    organization: Cloudmason
    credential_type: Machine
    inputs:
      username: awx
      password: "{{ lookup('env', 'AWX_CREDENTIALS_CLOUDMASON_AWX_PASSWORD') | b64decode }}"
      ssh_key_data: "{{ lookup('env', 'AWX_CREDENTIALS_CLOUDMASON_AWX_SSH_KEY') | b64decode }}"
  - name: Cloudmason Machine (mark)
    description: Cloudmason
    organization: Cloudmason
    credential_type: Machine
    inputs:
      username: mark
      password: "{{ lookup('env', 'AWX_CREDENTIALS_CLOUDMASON_MARK_PASSWORD') | b64decode }}"
      ssh_key_data: "{{ lookup('env', 'AWX_CREDENTIALS_CLOUDMASON_MARK_SSH_KEY') | b64decode }}"
      ssh_key_unlock: "{{ lookup('env', 'AWX_CREDENTIALS_CLOUDMASON_MARK_SSH_KEY_UNLOCK') | b64decode }}"
  - name: Cloudmason Machine (mamercad)
    description: Cloudmason
    organization: Cloudmason
    credential_type: Machine
    inputs:
      username: mamercad
      ssh_key_data: "{{ lookup('env', 'AWX_CREDENTIALS_CLOUDMASON_MAMERCAD_SSH_KEY') | b64decode }}"
      ssh_key_unlock: "{{ lookup('env', 'AWX_CREDENTIALS_CLOUDMASON_MAMERCAD_SSH_KEY_UNLOCK') | b64decode }}"
  - name: Cloudmason Vault
    description: Cloudmason Vault
    organization: Cloudmason
    credential_type: Vault
    inputs:
      vault_id: Cloudmason
      vault_password: "{{ lookup('env', 'AWX_CREDENTIALS_CLOUDMASON_VAULT_PASSWORD') | b64decode }}"
