projects:
  - name: Cloudmason
    description: Cloudmason
    organization: Cloudmason
    scm_type: git
    scm_url: https://github.com/mamercad/mamercad.cloudmason.git
    scm_branch: main
    scm_allow_override: true
    scm_clean: true
    scm_delete_on_update: true
    scm_update_on_launch: true
    scm_update_cache_timeout: 3600
  - name: Ansible Tower Samples / test
    description: Ansible Tower Samples / test
    organization: Cloudmason
    scm_type: git
    scm_url: https://github.com/mamercad/ansible-tower-samples.git
    scm_branch: test
    scm_allow_override: true
    scm_clean: true
    scm_delete_on_update: true
    scm_update_on_launch: true
    scm_update_cache_timeout: 3600
    default_environment: ansible-ee
