- name: figure out wan addresses
  ansible.builtin.shell:  # noqa no-changed-when
    cmd: /opt/vyatta/bin/vyatta-show-interfaces | grep 'inet ' | grep {{ interface }} | awk '{print $2}' | sed 's/\/.*$//'
  loop: "{{ interfaces }}"
  loop_control:
    loop_var: interface
  register: addresses

- name: set facts  # noqa var-naming
  ansible.builtin.set_fact:
    "{{ item.interface }}": "{{ item.stdout | trim }}"
  loop: "{{ addresses.results }}"

- name: ensure
  ansible.builtin.assert:
    that:
      - interface is defined
      - interface | length > 0
  loop: "{{ interfaces }}"
  loop_control:
    loop_var: interface

- name: debug
  ansible.builtin.debug:
    msg: |
      eth0: {{ eth0 }}
      eth1: {{ eth1 }}
      eth2: {{ eth2 }}
  loop: "{{ interfaces }}"
  loop_control:
    loop_var: interface
