all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ lookup('ansible.builtin.pipe', 'which python3') }}"
    prodesk:
      ansible_host: 192.168.1.127
      ansible_user: concourse
      ansible_python_interpreter: /usr/bin/python3
  children:
    linux:
      hosts:
        prodesk:
    ubuntu:
      hosts:
        prodesk:
