all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ lookup('ansible.builtin.pipe', 'which python3') }}"
    gateway:
      ansible_host: 192.168.1.1
      ansible_user: mamercad
      ansible_python_interpreter: /usr/bin/python
      interfaces: ['eth0', 'eth1', 'eth1.15', 'eth2']
    lenovo:
      ansible_host: 192.168.1.98
      ansible_user: concourse
      ansible_python_interpreter: /usr/bin/python3
    prodesk:
      ansible_host: 192.168.1.127
      ansible_user: concourse
      ansible_python_interpreter: /usr/bin/python3
    thinkpad:
      ansible_host: 192.168.1.67
      ansible_user: concourse
      ansible_python_interpreter: /usr/bin/python3
  children:
    linux:
      hosts:
        prodesk:
    pdns:
      hosts:
        # net1:
        # net2:
        thinkpad:
    ubuntu:
      hosts:
        prodesk:
  vars:
    mail:
      cloudmason_org:
        forwarders:
          - host: mx01.mail.icloud.com.
            weight: 10
          - host: mx02.mail.icloud.com.
            weight: 20
        txt: apple-domain=HkIuRA8FQ3S9jqP5
        spf: v=spf1 redirect=icloud.com
        dkim:
          host: sig1._domainkey
          value: sig1.dkim.cloudmason.org.at.icloudmailadmin.com.
      letsbuildthe_cloud:
        forwarders:
          - host: mx01.mail.icloud.com.
            weight: 10
          - host: mx02.mail.icloud.com.
            weight: 20
        txt: apple-domain=U1v3mEgKU1rZSMVn
        spf: v=spf1 redirect=icloud.com
        dkim:
          host: sig1._domainkey
          value: sig1.dkim.letsbuildthe.cloud.at.icloudmailadmin.com.
