- name: add Concourse chart repo
  kubernetes.core.helm_repository:
    state: present
    name: concourse-charts
    repo_url: https://concourse-charts.storage.googleapis.com/

- name: create concourse-main namespace
  kubernetes.core.k8s:
    state: present
    context: "{{ context }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: concourse-main
        labels:
          app.kubernetes.io/managed-by: Helm
        annotations:
          meta.helm.sh/release-name: concourse
          meta.helm.sh/release-namespace: concourse-main

- name: deploy latest version of Concourse
  kubernetes.core.helm:
    state: present
    context: "{{ context }}"
    name: concourse
    chart_ref: concourse/concourse
    release_namespace: concourse-main
    wait: true
    replace: true
    update_repo_cache: true
    disable_hook: true
    values: "{{ helm_values }}"

- name: patch the local-users secret
  kubernetes.core.k8s:
    state: patched
    kind: Secret
    name: concourse-web
    namespace: concourse-main
    definition:
      data:
        local-users: "{{ local_users | b64encode }}"
  notify: restart-concourse
