- name: create metallb clusterrole
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        labels:
          app: metallb
        name: metallb-system:controller
      rules:
        - apiGroups:
            - ""
          resources:
            - services
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ""
          resources:
            - services/status
          verbs:
            - update
        - apiGroups:
            - ""
          resources:
            - events
          verbs:
            - create
            - patch
        - apiGroups:
            - policy
          resourceNames:
            - controller
          resources:
            - podsecuritypolicies
          verbs:
            - use

- name: create metallb clusterrole
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        labels:
          app: metallb
        name: metallb-system:speaker
      rules:
        - apiGroups:
            - ""
          resources:
            - services
            - endpoints
            - nodes
          verbs:
            - get
            - list
            - watch
        - apiGroups: ["discovery.k8s.io"]
          resources:
            - endpointslices
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - ""
          resources:
            - events
          verbs:
            - create
            - patch
        - apiGroups:
            - policy
          resourceNames:
            - speaker
          resources:
            - podsecuritypolicies
          verbs:
            - use
