- name: create metallb deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app: metallb
          component: controller
        name: controller
        namespace: metallb-system
      spec:
        revisionHistoryLimit: 3
        selector:
          matchLabels:
            app: metallb
            component: controller
        template:
          metadata:
            annotations:
              prometheus.io/port: '7472'
              prometheus.io/scrape: 'true'
            labels:
              app: metallb
              component: controller
          spec:
            containers:
            - args:
              - --port=7472
              - --config=config
              env:
              - name: METALLB_ML_SECRET_NAME
                value: memberlist
              - name: METALLB_DEPLOYMENT
                value: controller
              image: quay.io/metallb/controller:v0.10.2
              name: controller
              ports:
              - containerPort: 7472
                name: monitoring
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - all
                readOnlyRootFilesystem: true
            nodeSelector:
              kubernetes.io/os: linux
            securityContext:
              runAsNonRoot: true
              runAsUser: 65534
            serviceAccountName: controller
            terminationGracePeriodSeconds: 0
