- name: create metallb role
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        labels:
          app: metallb
        name: config-watcher
        namespace: metallb-system
      rules:
        - apiGroups:
            - ""
          resources:
            - configmaps
          verbs:
            - get
            - list
            - watch

- name: create metallb role
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        labels:
          app: metallb
        name: pod-lister
        namespace: metallb-system
      rules:
        - apiGroups:
            - ""
          resources:
            - pods
          verbs:
            - list

- name: create metallb role
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        labels:
          app: metallb
        name: controller
        namespace: metallb-system
      rules:
        - apiGroups:
            - ""
          resources:
            - secrets
          verbs:
            - create
        - apiGroups:
            - ""
          resources:
            - secrets
          resourceNames:
            - memberlist
          verbs:
            - list
        - apiGroups:
            - apps
          resources:
            - deployments
          resourceNames:
            - controller
          verbs:
            - get
