- name: create metallb secret
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      data:
        secretkey: "{{ secretkey }}"
      kind: Secret
      metadata:
        name: memberlist
        namespace: metallb-system
      type: Opaque
