- name: create organizations
  awx.awx.tower_organization:
    state: present
    name: "{{ item.name }}"
    description: "{{ item.description }}"
  loop: "{{ organizations | default([], true) }}"

- name: create teams
  awx.awx.tower_team:
    state: present
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization }}"
  loop: "{{ teams | default([], true) }}"

- name: create projects
  awx.awx.tower_project:
    state: present
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    scm_type: "{{ item.scm_type }}"
    scm_url: "{{ item.scm_url }}"
  loop: "{{ projects | default([], true) }}"

- name: create inventories
  awx.awx.tower_inventory:
    state: present
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization }}"
  loop: "{{ inventories | default([], true) }}"

- name: create inventory sources
  awx.awx.tower_inventory_source:
    state: present
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization }}"
    inventory: "{{ item.inventory }}"
    source: "{{ item.source }}"
    source_project: "{{ item.source_project }}"
    source_path: "{{ item.source_path }}"
    overwrite: "{{ item.overwrite }}"
    update_cache_timeout: "{{ item.update_cache_timeout }}"
    update_on_project_update: "{{ item.update_on_project_update }}"
  loop: "{{ inventory_sources | default([], true) }}"
