- name: create credentials
  awx.awx.tower_credential:
    state: present
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization }}"
    credential_type: "{{ item.credential_type }}"
    inputs: "{{ item.inputs }}"
  loop: "{{ credentials | default([], true) }}"
  no_log: true
