# - name: deploy awx settings
#   awx.awx.tower_settings:
#     settings:
#       AUTH_LDAP_BIND_PASSWORD: "password"
#       AUTH_LDAP_USER_ATTR_MAP:
#         email: "mail"
#         first_name: "givenName"
#         last_name: "surname"
#     ...stage
