- name: create teams
  awx.awx.tower_team:
    state: present
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization }}"
  loop: "{{ teams | default([], true) }}"
