---

- name: download the release
  ansible.builtin.get_url:
    url: https://github.com/k3s-io/k3s/releases/download/{{ version }}/{{ binary }}
    dest: /tmp/k3s
    checksum: sha256:{{ sha256 }}
    owner: root
    group: root
    mode: 0755
  become: true

- name: move the release
  ansible.builtin.copy:
    src: /tmp/k3s
    remote_src: true
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  become: true

- name: deploy the unit
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0644
  become: true

- name: start and enable
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: true
  become: true

- name: fetch the kubeconfig
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  become: true
  register: kubeconfig
  when: fetch_kubeconfig | default(false, true)

- name: show the kubeconfig
  ansible.builtin.pause:
    minutes: 0
    prompt: "{{ kubeconfig.content | b64decode }}"
  delegate_to: localhost
  when: fetch_kubeconfig | default(false, true)
