---

inputs:
  - name: source

platform: linux

image_resource:
  type: registry-image
  source:
    repository: mamercad/alpine-ansible
    tag: latest

params:
  TOWER_HOST: ((awx-host))
  TOWER_USERNAME: ((awx-username))
  TOWER_PASSWORD: ((awx-password))
  PROJECT_NAME: ((.:awx.project.name))
  PROJECT_DESCRIPTION: ((.:awx.project.description))
  PROJECT_ORGANIZATION: ((.:awx.project.organization))
  PROJECT_SCM_TYPE: ((.:awx.project.scm_type))
  PROJECT_SCM_URL: ((.:awx.project.scm_url))
  PROJECT_SCM_BRANCH: ((.:awx.project.scm_branch))

run:
  dir: source
  path: /bin/ash
  args:
    - -o
    - pipefail
    - -c
    - |
      stty cols 120
      source /venv/bin/activate
      # awx ping 2>&1 | tee -a ../files/output
      # rc=$?

      awx projects get \
        --conf.format yaml \
        $PROJECT_NAME \
        2>&1 | tee -a ../files/before

      awx projects modify \
        --name $PROJECT_NAME \
        --description $PROJECT_DESCRIPTION \
        --scm_type $PROJECT_SCM_TYPE \
        --scm_url $PROJECT_SCM_URL \
        --scm_branch $PROJECT_SCM_BRANCH \
        $PROJECT_NAME \
        2>&1 | tee -a ../files/output
      rc=$?

      awx projects get \
        --conf.format yaml \
        $PROJECT_NAME \
        2>&1 | tee -a ../files/after

      echo "AWX Project $PROJECT_NAME before/after diff (rc=$rc):" | tee -a ../files/slack
      echo ""                                                      | tee -a ../files/slack
      diff ../files/before ../files/after                          | tee -a ../files/slack

      # last 10 lines for slack
      # tail -10 ../files/output | tee -a ../files/slack

      # add backticks to output
      sed -i '1s/^/```\n/' ../files/output
      sed -i '$s/$/\n```/' ../files/output

      # add backticks to slack
      # sed -i '1s/^/```(last 10 lines)\n/' ../files/slack
      sed -i '1s/^/```\n/' ../files/slack
      sed -i '$s/$/\n```/' ../files/slack

      exit $rc

outputs:
  - name: files
