---

resource_types:

  - name: slack-alert
    type: docker-image
    source:
      repository: arbourd/concourse-slack-alert-resource

resources:

  - name: source
    type: git
    icon: github
    source:
      uri: https://github.com/mamercad/mamercad.cloudmason.git
      branch: main
      paths: roles/octodns

  - name: notify
    type: slack-alert
    source:
      url: ((site.SLACK_WEBHOOK))

jobs:

  - name: deploy
    public: true
    plan:

      - get: source
        trigger: true

      - task: ansible
        params:
          ANSIBLE_FORCE_COLOR: true
          CONCOURSE_SSH_KEY: ((awx.CONCOURSE_SSH_KEY))
          AWX_CREDENTIALS_CLOUDMASON_MAMERCAD_SSH_KEY: ((awx/credentials/mamercad.ssh_key))
          AWX_CREDENTIALS_CLOUDMASON_MAMERCAD_SSH_KEY_UNLOCK: ((awx/credentials/mamercad.ssh_key_unlock))
          OCTODNS_CLOUDFLARE_API_KEY: ((octodns/cloudflare.api_key))
          OCTODNS_POWERDNS_API_KEY: ((octodns/powerdns.api_key))
        config:
          inputs:
            - name: source
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: mamercad/alpine-ansible
              tag: latest
          run:
            path: /bin/ash
            args:
              - -exc
              - |
                stty cols 120

                eval $(ssh-agent)

                touch concourse.key
                chmod 600 concourse.key
                echo "${CONCOURSE_SSH_KEY}" >concourse.key
                ssh-add concourse.key

                touch mamercad.key
                chmod 600 mamercad.key
                echo "${AWX_CREDENTIALS_CLOUDMASON_MAMERCAD_SSH_KEY}" >mamercad.key
                echo "${AWX_CREDENTIALS_CLOUDMASON_MAMERCAD_SSH_KEY_UNLOCK}" \
                  | SSH_ASKPASS=/bin/cat setsid -c ssh-add mamercad.key

                ssh-add -l

                source /venv/bin/activate
                cd source
                ansible-playbook -i inventory/concourse.yml octodns.yml -v

        on_success:
          put: notify
          params:
            alert_type: success
        on_failure:
          put: notify
          params:
            alert_type: failed
        on_abort:
          put: notify
          params:
            alert_type: aborted
        on_error:
          put: notify
          params:
            alert_type: errored
