---

resource_types:

  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:

  # - name: source
  #   type: git
  #   icon: github
  #   source:
  #     uri: https://github.com/mamercad/mamercad.cloudmason.git

  - name: pull-request
    type: pull-request
    check_every: 24h
    source:
      repository: mamercad/mamercad.cloudmason
      access_token: ((github-access-token))

jobs:

  - name: test-pr
    plan:

      - get: pull-request
        trigger: true
        version: every

      - put: pull-request
        params:
          path: pull-request
          status: pending

      - task: test-pr
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: alpine/git, tag: "latest"}
          inputs:
            - name: pull-request
          run:
            path: /bin/sh
            args:
              - -xce
              - |
                cd pull-request
                git log --graph --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s" | head > ../files/log.txt
                cat ../files/log.txt
          outputs:
            - name: files
        on_failure:
          put: pull-request
          params:
            path: pull-request
            status: failure

      - put: pull-request
        params:
          path: pull-request
          status: success
          comment: "Concourse tests passed :tada:"
          comment_file: ./files/log.txt
