---

# vault kv put concourse/main/site \
#   SLACK_WEBHOOK="$(lpass show 'Homelab\Concourse/Slack' --notes)" \
#   CONCOURSE_SSH_KEY="$(lpass show 'Homelab\Concourse/concourse.key' --notes)"

resource_types:

  - name: slack-alert
    type: docker-image
    source:
      repository: arbourd/concourse-slack-alert-resource

resources:

  - name: source
    type: git
    icon: github
    source:
      uri: https://github.com/mamercad/mamercad.cloudmason.git
      branch: main

  - name: notify
    type: slack-alert
    source:
      url: ((site.SLACK_WEBHOOK))

jobs:

  - name: lint
    public: true
    plan:

      - get: source
        trigger: true

      - task: lint
        config:
          inputs:
            - name: source
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: mamercad/alpine-ansible
              tag: latest
          run:
            path: /bin/ash
            args:
              - -exc
              - |
                stty cols 120
                source /venv/bin/activate
                cd source
                ansible-lint -v
        on_success:
          put: notify
          params:
            alert_type: success
        on_failure:
          put: notify
          params:
            alert_type: failed
        on_abort:
          put: notify
          params:
            alert_type: aborted
        on_error:
          put: notify
          params:
            alert_type: errored

  - name: deploy
    public: true
    plan:

      - get: source
        passed: ['lint']
        trigger: true

      - task: ansible
        params:
          CONCOURSE_SSH_KEY: ((site.CONCOURSE_SSH_KEY))
        config:
          inputs:
            - name: source
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: mamercad/alpine-ansible
              tag: latest
          run:
            path: /bin/ash
            args:
              - -exc
              - |
                stty cols 120

                touch concourse.key
                chmod 600 concourse.key
                echo "${CONCOURSE_SSH_KEY}" >concourse.key
                eval $(ssh-agent)
                ssh-add concourse.key
                ssh-add -l

                source /venv/bin/activate
                cd source
                ansible -i inventory/concourse.yml -m ping all
                ansible-playbook -i inventory/concourse.yml site.yml -v

        on_success:
          put: notify
          params:
            alert_type: success
        on_failure:
          put: notify
          params:
            alert_type: failed
        on_abort:
          put: notify
          params:
            alert_type: aborted
        on_error:
          put: notify
          params:
            alert_type: errored
