# Following: https://docs.docker.com/engine/install/ubuntu/

- name: remove docker docker-engine docker.io containerd runc
  ansible.builtin.apt:
    state: absent
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
  become: true

- name: install apt-transport-https ca-certificates curl gnupg lsb-release
  ansible.builtin.apt:
    state: present
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: true

- name: install Docker's GPG key
  ansible.builtin.apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  become: true

- name: deploy Docker's Apt repository
  ansible.builtin.apt_repository:
    state: present
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
  become: true

- name: install docker-ce docker-ce-cli containerd.io
  ansible.builtin.apt:
    state: present
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: true

- name: add folks to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_admins | default([], true) }}"
  become: true
