---
- name: concourse
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: include concourse role (main tasks)
      ansible.builtin.include_role:
        name: concourse
        tasks_from: main.yml
      vars:
        context: thinkpad
        helm_values:
          replicas: 1
          web.service.api.type: LoadBalancer
          web.service.workerGateway.type: LoadBalancer
          concourse.web.externalUrl: https://concourse.cloudmason.org
