---
- name: fail
  hosts: "{{ ansible_limit | default('all', true) }}"
  connection: "{{ 'local' if ansible_limit | default('all', true) == 'localhost' else 'ssh' }}"
  gather_facts: false
  become: false
  tasks:

    - name: fail randomly
      ansible.builtin.fail:
      when: 3 | random == 1

  post_tasks:

    - name: show all hosts
      run_once: true
      ansible.builtin.debug:
        msg: |
          all hosts:
          {{ ansible_play_hosts_all
          | join(', ') }}

    - name: show passed hosts
      run_once: true
      ansible.builtin.debug:
        msg: |
          passed hosts:
          {{ ansible_play_batch
          | join(', ') }}

    - name: show failed hosts
      run_once: true
      ansible.builtin.debug:
        msg: |
          failed hosts:
          {{ ansible_play_hosts_all
          | difference(ansible_play_batch)
          | join(', ') }}
