---
- name: k3s
  hosts: "{{ ansible_limit | default('all', true) }}"
  connection: "{{ 'local' if ansible_limit | default('all', true) == 'localhost' else 'ssh' }}"
  gather_facts: true
  become: false
  tasks:
    - name: include k3s role (main tasks)
      ansible.builtin.include_role:
        name: k3s
        tasks_from: main.yml
