---
- name: tailscale
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - name: include secrets role (main tasks)
      ansible.builtin.include_role:
        name: secrets
        tasks_from: main.yml
      vars:
        maps:
          - lastpass: Homelab\Vault/root
            vault: Homelab/Vault/root
