---
- name: site
  hosts: "{{ ansible_limit | default('all', True) }}"
  connection: "{{ 'local' if ansible_limit | default('all', True) == 'localhost' else 'ssh' }}"
  gather_facts: false
  become: false
  tasks:
    - name: ping
      action: ping

- name: powerdns
  hosts: powerdns
  connection: "{{ 'local' if ansible_limit | default('all', True) == 'localhost' else 'ssh' }}"
  gather_facts: true
  become: false
  tasks:
    - name: include powerdns role (rasbian tasks)
      ansible.builtin.include_role:
        name: powerdns
        tasks_from: raspian.yml
      when: ansible_architecture == "armv7l"
