---
- name: statsd
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks:
    - name: include statsd role (main tasks)
      ansible.builtin.include_role:
        name: statsd
        tasks_from: main.yml
      vars:
        context: thinkpad
