---
- name: wtf
  hosts: "{{ ansible_limit | default('all', true) }}"
  connection: "{{ 'local' if ansible_limit | default('all', true) == 'localhost' else 'ssh' }}"
  gather_facts: true
  become: false
  tasks:
    - name: setup
      ansible.builtin.debug:
        msg: |
          Vendor: {{ ansible_chassis_vendor }}
          Uptime: {{ ansible_uptime_seconds }}
