---
- name: wtf
  hosts: "{{ ansible_limit | default('all', true) }}"
  connection: "{{ 'local' if ansible_limit | default('all', true) == 'localhost' else 'ssh' }}"
  gather_facts: true
  become: false
  tasks:
    - name: setup
      ansible.builtin.debug:
        msg: |
          Vendor: {{ ansible_chassis_vendor }}
          Product Name: {{ ansible_product_name }}
          Product Version: {{ ansible_product_version }}
          Uptime: {{ ansible_uptime_seconds }}
          Distribution: {{ ansible_distribution }}
          Release: {{ ansible_distribution_release }}
          Version: {{ ansible_distribution_version }}
          DNS0 Nameserver: {{ ansible_dns.nameservers.0 | default('Undefined', true) }}
          DNS0 Search: {{ ansible_dns.search.0 | default('Undefined', true) }}
          Domain: {{ ansible_domain }}
          FQDN: {{ ansible_fqdn }}
          Hostname: {{ ansible_hostname }}
          Kernel: {{ ansible_kernel_version }}
          Machine: {{ ansible_machine }}
          Processors: {{ ansible_processor_nproc }}
          Memory: {{ ansible_memtotal_mb }}
