name: integration

on:
  pull_request_target:
    branches: [ main ]

jobs:

  approve:
    name: approve
    runs-on: ubuntu-latest
    steps:
      - name: approve
        run: echo All pull requests need to be approved before running the integration tests.

  integrations:
    name: integration
    needs: [ approve ]
    environment: integration
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mamercad/cloudmason/ansible

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: mamercad/cloudmason
          ref: ${{ github.event.pull_request.head.sha }} # Check out the pull request

      - name: Ping Healthchecks.io
        uses: wei/curl@master
        with:
          args: ${HEALTHCHECKS_IO}
