name: integration

on:
  pull_request_target:
    branches: [ main ]

jobs:

  integration:
    name: integration
    environment: integration
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: mamercad/cloudmason
          ref: ${{ github.event.pull_request.head.sha }} # Check out the pull request

      - name: Ping Healthchecks.io
        run: |
          curl --silent --head ${{ secrets.HEALTHCHECKS_IO }}
