# https://dev.to/petrsvihlik/using-environment-protection-rules-to-secure-secrets-when-building-external-forks-with-pullrequesttarget-hci
name: integration

on:
  pull_request_target:
    branches: [ main ]

jobs:

  approve:
    name: approve
    runs-on: ubuntu-latest
    steps:
      - name: approve
        run: echo All pull requests need to be approved before running the integration tests.

  store-secret:
    name: store-secret
    needs: [ approve ]
    environment: integration
    runs-on: ubuntu-latest
    steps:
      - name: store-secret
        shell: bash
        run: |
          run: echo "${{ secrets.HEALTHCHECKS_IO }}" >secret
      - name: upload-secret
        uses: actions/upload-artifact@v2
        with:
          name: secret
          path: secret
          retention-days: 0

  integration:
    name: integration
    needs: [ store-secret ]
    runs-on: ubuntu-latest
    steps:
      - name: download-secret
        uses: actions/download-artifact@v2
        with:
          name: secret
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: mamercad/cloudmason
          ref: ${{ github.event.pull_request.head.sha }} # Check out the pull request
      - name: Ping Healthchecks.io
        run: |
          source secret
          curl -vvv ${HEALTHCHECKS_IO}
