name: integration

on:
  pull_request_target:
    types: [labeled]

jobs:

  ansible-lint:

    name: integration

    environment: integration
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mamercad/cloudmason/ansible

    steps:

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: mamercad/cloudmason

      - name: Ping Healthchecks.io
        run: |
          which curl
          curl -v
          curl ${HEALTHCHECKS_IO}
